name: First Workflow
on: [push]
jobs: 
  shell-commands:
    runs-on: ubuntu-latest
    steps: 
        - name: print a string
          run: echo "Hello World"
        - name: list the file
          run: |
           - pwd
           - ls -ltr
