name: First Workflow
on: [push]
jobs: 
  shell-commands:
    runs-on: ubuntu-latest
    steps: 
        - name: print a string
          run: echo "Hello World"
        - name: list the file
          run: |
            touch test
            ls -ltr
  Parellel-jobs:
    runs-on: macos-latest 
    steps:
      - name: view sw version
        run: sw_vers
  dependent-jobs:
    runs-on: windows-latest
    needs: shell-commands
    steps:
      - name: print a string
        run: Write-Output "Windows String"